"""
AI Ops Agent - 智能运维 Agent 核心模块

后端使用方式:
    from ai_ops_agent import AgentOrchestrator, AgentConfiguration

    config = AgentConfiguration(llm=LLMConfiguration(...))
    agent = AgentOrchestrator(config)
    response = await agent.handle_user_message(session_id, message)
"""

from utils.toolFunction.config import (
    AgentConfiguration,
    LLMConfiguration,
    SafetyConfiguration,
)
from utils.toolFunction.models import (
    CpuInfo,
    DatabaseInstallInfo,
    DatabaseStatus,
    DiskPartitionInfo,
    DockerContainer,
    DockerInstallInfo,
    FileInfo,
    FileOperationResult,
    FileType,
    FirewallBackendType,
    FirewallPortOperationResult,
    FirewallPortRule,
    FirewallStatus,
    GpuInfo,
    GrepMatch,
    GrepResult,
    LoginRecord,
    LogQueryResult,
    MemoryInfo,
    MessageRole,
    NetworkInterfaceInfo,
    NginxInstallInfo,
    NginxStatus,
    OperationResult,
    OwnerChangeResult,
    PermissionChangeResult,
    PingResult,
    PortCheckResult,
    ProcessInfo,
    ProcessKillResult,
    ProcessSortBy,
    ServiceAction,
    ServiceOperationResult,
    SystemVersion,
    UptimeInfo,
    UserInfo,
)
from utils.toolFunction.models.agent.chat_models import AgentResponse, ChatMessage
from utils.toolFunction.tools import (
    addFirewallPort,
    applySslCertificate,
    createNginxSite,
    autoCleanProcesses,
    batchKillProcesses,
    changeOwner,
    changePermissions,
    checkDatabaseInstalled,
    testMysqlConnection,
    checkDockerInstalled,
    checkNginxInstalled,
    checkPortConnectivity,
    compressPath,
    configSslForNginx,
    copyFile,
    createDockerContainer,
    createDirectory,
    createFile,
    createMysqlDatabase,
    createMysqlUserAndGrant,
    decompressArchive,
    deleteDockerContainer,
    deleteDirectory,
    deleteFile,
    deleteNginxSite,
    detectNginxLayout,
    getCpuInfo,
    getDatabaseStatus,
    getDiskInfo,
    getDockerContainerInfo,
    getDockerContainerList,
    getDockerContainerLogs,
    getDockerContainers,
    getDockerImageList,
    getDockerDaemonConfig,
    searchDockerImages,
    setDockerRegistryMirror,
    _buildDaemonConfigPayload,
    getDirectoryTree,
    getEnvironmentVariables,
    getFirewallStatus,
    getGpuInfo,
    getLoginHistory,
    getMemoryInfo,
    getMysqlDatabaseList,
    getNetworkInfo,
    getNginxSiteConfig,
    updateNginxSiteConfig,
    _getNginxSiteUpdateInfo,
    getNginxSiteList,
    getNginxStatus,
    generateProxyConfig,
    generateStaticSiteConfig,
    getProcessDetail,
    getSystemVersion,
    getUptime,
    getZombieOrphanProcesses,
    isTextFile,
    killProcess,
    listDirectory,
    listFirewallPorts,
    listProcesses,
    listSingleFileOrDirectory,
    grepFileOrDirectory,
    listUsers,
    manageSystemService,
    pingHost,
    pullDockerImage,
    querySystemLogs,
    readTextFile,
    reCreateDockerContainer,
    removeFirewallPort,
    renameFileOrDirectory,
    reloadNginx,
    renewSslCertificate,
    restartDockerContainer,
    restartNginx,
    saveNginxConfig,
    startDockerContainer,
    stopDockerContainer,
    testNginxConfig,
    updateContainerEnv,
    updateContainerPorts,
    updateContainerVolumes,
    writeTextFile,
    # 内部辅助（供 Service 层导入）
    _getCreateDbInfo,
    _getCreateUserInfo,
    _getDatabaseListSql,
    _getNginxConfigWriteInfo,
    _getNginxSiteDeleteInfo,
)

ALL_TOOL_FUNCTIONS = [
    # 防火墙
    getFirewallStatus,
    listFirewallPorts,
    addFirewallPort,
    removeFirewallPort,
    # 系统监控
    getCpuInfo,
    getMemoryInfo,
    getDiskInfo,
    getGpuInfo,
    getNetworkInfo,
    # 文件系统
    listDirectory,
    listSingleFileOrDirectory,
    grepFileOrDirectory,
    getDirectoryTree,
    copyFile,
    isTextFile,
    compressPath,
    decompressArchive,
    readTextFile,
    writeTextFile,
    createFile,
    createDirectory,
    deleteFile,
    deleteDirectory,
    renameFileOrDirectory,
    changePermissions,
    changeOwner,
    # 进程
    listProcesses,
    killProcess,
    getProcessDetail,
    autoCleanProcesses,
    getZombieOrphanProcesses,
    batchKillProcesses,
    # 日志
    querySystemLogs,
    # 用户
    listUsers,
    getLoginHistory,
    # 网络诊断
    pingHost,
    checkPortConnectivity,
    # 系统信息
    getSystemVersion,
    getUptime,
    getEnvironmentVariables,
    # Docker
    checkDockerInstalled,
    getDockerContainers,
    getDockerImageList,
    pullDockerImage,
    searchDockerImages,
    setDockerRegistryMirror,
    updateContainerEnv,
    updateContainerPorts,
    updateContainerVolumes,
    reCreateDockerContainer,
    getDockerContainerInfo,
    createDockerContainer,
    updateNginxSiteConfig,
    deleteDockerContainer,
    startDockerContainer,
    stopDockerContainer,
    restartDockerContainer,
    getDockerContainerList,
    getDockerContainerLogs,
    # Nginx
    checkNginxInstalled,
    getNginxStatus,
    generateStaticSiteConfig,
    generateProxyConfig,
    saveNginxConfig,
    testNginxConfig,
    reloadNginx,
    restartNginx,
    createNginxSite,
    getNginxSiteConfig,
    getNginxSiteList,
    deleteNginxSite,
    applySslCertificate,
    configSslForNginx,
    renewSslCertificate,
    # 数据库
    checkDatabaseInstalled,
    getDatabaseStatus,
    testMysqlConnection,
    createMysqlDatabase,
    createMysqlUserAndGrant,
    getMysqlDatabaseList,
    # Nginx 布局检测
    detectNginxLayout,
    # 服务管理
    manageSystemService,
]

__all__ = [
    "AgentConfiguration",
    "LLMConfiguration",
    "SafetyConfiguration",
    "AgentResponse",
    "ChatMessage",
    # 常用实体类（models）
    "MessageRole",
    "OperationResult",
    "FirewallBackendType",
    "FirewallStatus",
    "FirewallPortRule",
    "FirewallPortOperationResult",
    "CpuInfo",
    "MemoryInfo",
    "DiskPartitionInfo",
    "GpuInfo",
    "NetworkInterfaceInfo",
    "FileType",
    "FileInfo",
    "FileOperationResult",
    "GrepMatch",
    "GrepResult",
    "PermissionChangeResult",
    "OwnerChangeResult",
    "ProcessSortBy",
    "ProcessInfo",
    "ProcessKillResult",
    "LogQueryResult",
    "UserInfo",
    "LoginRecord",
    "PingResult",
    "PortCheckResult",
    "SystemVersion",
    "UptimeInfo",
    "DockerInstallInfo",
    "DockerContainer",
    "NginxInstallInfo",
    "NginxStatus",
    "DatabaseInstallInfo",
    "DatabaseStatus",
    "ServiceAction",
    "ServiceOperationResult",
    "ALL_TOOL_FUNCTIONS",
    # 防火墙
    "getFirewallStatus",
    "listFirewallPorts",
    "addFirewallPort",
    "removeFirewallPort",
    # 系统监控
    "getCpuInfo",
    "getMemoryInfo",
    "getDiskInfo",
    "getGpuInfo",
    "getNetworkInfo",
    # 文件系统
    "listDirectory",
    "createFile",
    "createDirectory",
    "deleteFile",
    "deleteDirectory",
    "renameFileOrDirectory",
    "changePermissions",
    "changeOwner",
    "listSingleFileOrDirectory",
    "grepFileOrDirectory",
    "getDirectoryTree",
    "copyFile",
    "isTextFile",
    "compressPath",
    "decompressArchive",
    "readTextFile",
    "writeTextFile",
    # 进程
    "listProcesses",
    "killProcess",
    "getProcessDetail",
    "autoCleanProcesses",
    "getZombieOrphanProcesses",
    "batchKillProcesses",
    # 日志
    "querySystemLogs",
    # 用户
    "listUsers",
    "getLoginHistory",
    # 网络诊断
    "pingHost",
    "checkPortConnectivity",
    # 系统信息
    "getSystemVersion",
    "getUptime",
    "getEnvironmentVariables",
    # Docker
    "checkDockerInstalled",
    "getDockerContainers",
    "getDockerImageList",
    "pullDockerImage",
    "searchDockerImages",
    "setDockerRegistryMirror",
    "createDockerContainer",
    "startDockerContainer",
    "stopDockerContainer",
    "restartDockerContainer",
    "deleteDockerContainer",
    "getDockerContainerList",
    "getDockerContainerLogs",
    "getDockerContainerInfo",
    "updateContainerEnv",
    "updateContainerPorts",
    "updateContainerVolumes",
    "reCreateDockerContainer",
    # Nginx
    "checkNginxInstalled",
    "getNginxStatus",
    "generateStaticSiteConfig",
    "generateProxyConfig",
    "saveNginxConfig",
    "testNginxConfig",
    "reloadNginx",
    "restartNginx",
    "createNginxSite",
    "getNginxSiteConfig",
    "updateNginxSiteConfig",
    "getNginxSiteList",
    "deleteNginxSite",
    "applySslCertificate",
    "configSslForNginx",
    "renewSslCertificate",
    # 数据库
    "checkDatabaseInstalled",
    "getDatabaseStatus",
    "testMysqlConnection",
    "createMysqlDatabase",
    "createMysqlUserAndGrant",
    "getMysqlDatabaseList",
    # Nginx
    "detectNginxLayout",
    # 服务管理
    "manageSystemService",
]
