from utils.toolFunction.tools.ops.misc.database_tools import (
    checkDatabaseInstalled,
    createMysqlDatabase,
    createMysqlUserAndGrant,
    getDatabaseStatus,
    getMysqlDatabaseList,
    testMysqlConnection,
    _getCreateDbInfo,
    _getCreateUserInfo,
    _getDatabaseListSql,
)
from utils.toolFunction.tools.ops.misc.docker_tools import (
    checkDockerInstalled,
    createDockerContainer,
    deleteDockerContainer,
    getDockerContainerInfo,
    getDockerContainerList,
    getDockerContainerLogs,
    getDockerContainers,
    getDockerImageList,
    pullDockerImage,
    reCreateDockerContainer,
    restartDockerContainer,
    startDockerContainer,
    stopDockerContainer,
    updateContainerEnv,
    updateContainerPorts,
    updateContainerVolumes,
    searchDockerImages,
    getDockerDaemonConfig,
    _buildDaemonConfigPayload,
    setDockerRegistryMirror,
)
from utils.toolFunction.tools.ops.filesystem.filesystem_tools import (
    changeOwner,
    changePermissions,
    compressPath,
    copyFile,
    createDirectory,
    createFile,
    decompressArchive,
    deleteDirectory,
    deleteFile,
    getDirectoryTree,
    isTextFile,
    listDirectory,
    listSingleFileOrDirectory,
    grepFileOrDirectory,
    readTextFile,
    renameFileOrDirectory,
    writeTextFile,
)
from utils.toolFunction.tools.ops.firewall.firewall_tools import (
    addFirewallPort,
    getFirewallStatus,
    listFirewallPorts,
    removeFirewallPort,
)
from utils.toolFunction.tools.ops.misc.log_tools import querySystemLogs
from utils.toolFunction.tools.ops.network.network_tools import checkPortConnectivity, pingHost
from utils.toolFunction.tools.ops.misc.nginx_tools import (
    applySslCertificate,
    checkNginxInstalled,
    configSslForNginx,
    createNginxSite,
    deleteNginxSite,
    detectNginxLayout,
    generateProxyConfig,
    generateStaticSiteConfig,
    getNginxSiteConfig,
    getNginxSiteList,
    updateNginxSiteConfig,
    _getNginxSiteUpdateInfo,
    getNginxStatus,
    reloadNginx,
    renewSslCertificate,
    restartNginx,
    saveNginxConfig,
    testNginxConfig,
    _getNginxConfigWriteInfo,
    _getNginxSiteDeleteInfo,
)
from utils.toolFunction.tools.ops.process.process_tools import (
    autoCleanProcesses,
    batchKillProcesses,
    getProcessDetail,
    getZombieOrphanProcesses,
    killProcess,
    listProcesses,
)
from utils.toolFunction.tools.ops.service.service_tools import manageSystemService
from utils.toolFunction.tools.ops.misc.system_info_tools import (
    getEnvironmentVariables,
    getSystemVersion,
    getUptime,
)
from utils.toolFunction.tools.ops.monitor.system_monitor_tools import (
    getCpuInfo,
    getDiskInfo,
    getGpuInfo,
    getMemoryInfo,
    getNetworkInfo,
)
from utils.toolFunction.tools.ops.user.user_tools import getLoginHistory, listUsers

__all__ = [
    # 防火墙
    "getFirewallStatus",
    "listFirewallPorts",
    "addFirewallPort",
    "removeFirewallPort",
    # 系统监控
    "getCpuInfo",
    "getMemoryInfo",
    "getDiskInfo",
    "getGpuInfo",
    "getNetworkInfo",
    # 文件系统
    "listDirectory",
    "listSingleFileOrDirectory",
    "grepFileOrDirectory",
    "getDirectoryTree",
    "copyFile",
    "isTextFile",
    "compressPath",
    "decompressArchive",
    "readTextFile",
    "writeTextFile",
    "createFile",
    "createDirectory",
    "deleteFile",
    "deleteDirectory",
    "renameFileOrDirectory",
    "changePermissions",
    "changeOwner",
    # 进程
    "listProcesses",
    "killProcess",
    "getProcessDetail",
    "autoCleanProcesses",
    "getZombieOrphanProcesses",
    "batchKillProcesses",
    # 日志
    "querySystemLogs",
    # 用户
    "listUsers",
    "getLoginHistory",
    # 网络诊断
    "pingHost",
    "checkPortConnectivity",
    # 系统信息
    "getSystemVersion",
    "getUptime",
    "getEnvironmentVariables",
    # Docker
    "checkDockerInstalled",
    "getDockerContainers",
    "pullDockerImage",
    "getDockerImageList",
    "createDockerContainer",
    "startDockerContainer",
    "stopDockerContainer",
    "restartDockerContainer",
    "deleteDockerContainer",
    "getDockerContainerList",
    "getDockerContainerLogs",
    "getDockerContainerInfo",
    "updateContainerEnv",
    "updateContainerPorts",
    "updateContainerVolumes",
    "reCreateDockerContainer",
    "searchDockerImages",
    "getDockerDaemonConfig",
    "_buildDaemonConfigPayload",
    "setDockerRegistryMirror",
    # Nginx
    "checkNginxInstalled",
    "getNginxStatus",
    "detectNginxLayout",
    "generateStaticSiteConfig",
    "generateProxyConfig",
    "saveNginxConfig",
    "testNginxConfig",
    "reloadNginx",
    "restartNginx",
    "createNginxSite",
    "getNginxSiteConfig",
    "updateNginxSiteConfig",
    "_getNginxSiteUpdateInfo",
    "getNginxSiteList",
    "deleteNginxSite",
    "applySslCertificate",
    "configSslForNginx",
    "renewSslCertificate",
    "_getNginxConfigWriteInfo",
    "_getNginxSiteDeleteInfo",
    # 数据库
    "checkDatabaseInstalled",
    "getDatabaseStatus",
    "testMysqlConnection",
    "createMysqlDatabase",
    "createMysqlUserAndGrant",
    "getMysqlDatabaseList",
    "_getCreateDbInfo",
    "_getCreateUserInfo",
    "_getDatabaseListSql",
    # 服务管理
    "manageSystemService",
]
